//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoCMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Azienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Azienda()
        {
            this.Contatto = new HashSet<Contatto>();
            this.Indirizzo = new Indirizzo();
        }
    
        public int ID { get; set; }
        public string Ragione { get; set; }
        public string Piva { get; set; }
        public string CodFisc { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public string Note { get; set; }
        public string Creazione { get; set; }
    
        public Indirizzo Indirizzo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatto> Contatto { get; set; }
    }
}
