//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoCMA
{
    using System;
    
    public partial class Indirizzo
    {
        public string Civico { get; set; }
        public string Provincia { get; set; }
        public string Cap { get; set; }
        public string Citta { get; set; }
        public string Via { get; set; }
        public string Nazione { get; set; }
    }
}
