//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoCMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_RDO_Composizione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lista_RDO_Composizione()
        {
            this.RDO_Composizione = new HashSet<RDO_Composizione>();
        }
    
        public int ID { get; set; }
        public string Descrizione { get; set; }
        public string UnitaMisura { get; set; }
        public decimal Quantita { get; set; }
    
        public virtual Lista_RDO Associazione_Commessa_RDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDO_Composizione> RDO_Composizione { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
