//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoCMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordine_Composizione
    {
        public int ID { get; set; }
    
        public virtual ODA_Composizione RDA_Composizione { get; set; }
        public virtual Ordine Ordine { get; set; }
    }
}
