//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoCMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RDO()
        {
            this.RDO_Composizione = new HashSet<RDO_Composizione>();
        }
    
        public int ID { get; set; }
        public string Codice { get; set; }
        public string Progressivo { get; set; }
        public string Creazione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDO_Composizione> RDO_Composizione { get; set; }
        public virtual Lista_RDO Lista_RDO { get; set; }
        public virtual Fornitore Fornitore { get; set; }
    }
}
